runtime: python311
app_engine_apis: true
entrypoint: gunicorn -b :$PORT --workers 1 --threads 8 --timeout 60 main:app

instance_class: F1
automatic_scaling:
  max_instances: 4
  max_idle_instances: 1
  min_pending_latency: 5s
  max_pending_latency: 10s
  max_concurrent_requests: 50

error_handlers:
- error_code: over_quota
  file: over_quota.txt

handlers:
- url: /flags
  static_dir: flags
  expiration: "99d"
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
  expiration: "99d"
- url: /style\.css
  static_files: style.css
  upload: style\.css
- url: /ScoreExplanation
  static_files: ScoreExplanation.html
  upload: ScoreExplanation\.html
- url: /robots\.txt
  static_files: robots.txt
  upload: robots\.txt
- url: /googlea1fa86d6b3ddcb15\.html
  static_files: googlea1fa86d6b3ddcb15.html
  upload: googlea1fa86d6b3ddcb15\.html
